name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # check:
  #   runs-on: macos-12

  #   steps:

  #   - uses: actions/checkout@v1
  #   - name: SwiftLint
  #     run: ./.github/swiftlinter      

  build-test:
  
    runs-on: macos-12

    # needs: [check]

    strategy:
      matrix:
        platform: [macos, ios, tvos]
        xcode: ["13.4.1"]

    steps:
      
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    - name: Build/Test
      run: |
        make build-test-${{ matrix.platform }}

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: |
          TestResults
